:sparkles: Support export/import request to/from grpcurl command
rogchap/wombat pull request #51
Opened 2021-02-23 09:01 UTC by devkanro

# Description
This PR make wombat support export request to [grpcurl](https://github.com/fullstorydev/grpcurl) and import body and metadata from them.
Resolve the #50 

## Limit
### Export
TLS cert, Protobuf files will not be included in the exported command. Recommend using the service reflection.
Those configurations will export to grpcurl command.
- [x] host
- [ ] tls cert
- [ ] protos root
- [ ] protos file
- [x] reflection metadata
- [x] method
- [x] body
- [x] request metadata

### Import
Import will change your selected service, selected method, body, and metadata, but it will not change the workspace.
Those configurations will import from grpcurl command.
- [ ] host
- [ ] tls cert
- [ ] protos root
- [ ] protos file
- [ ] reflection metadata
- [x] method
- [x] body
- [x] request metadata

## Screenshot
![Snipaste_2021-02-23_16-40-48](https://user-images.githubusercontent.com/9367842/108819964-7d541880-75f6-11eb-998c-02c71d7e1416.png)
![Snipaste_2021-02-23_16-44-41](https://user-images.githubusercontent.com/9367842/108819965-7e854580-75f6-11eb-96cc-a8810634d34d.png)

## Co-Contributors
Frontend: @iou90
Backend: @devkanro

2021-03-08 01:26 UTC, rogchap commented
Wow. Thank you @devkanro and @iou90
Sorry for taking so long to look at this PR (had to move house recently 😞 )

2021-03-08 05:36 UTC, rogchap requested changes
Thanks again for this; I've added a few comments. All minor stuff.

Could you also update the `CHANGELOG.md` file; and not forget to add your attributions.

2021-03-08 05:36 UTC, rogchap commented on internal/app/api.go
> +		return fmt.Errorf("Method '%s' not found. ", method)
```suggestion
		return fmt.Errorf("method %q not found. ", method)
```

2021-03-08 05:36 UTC, rogchap commented on frontend/src/views/InputPane.svelte
> +	import { getContext } from 'svelte';
nitpick: spacing.
```suggestion
  import { getContext } from 'svelte';
```

2021-03-08 05:36 UTC, rogchap commented on .gitignore
> +.vscode
😱 :trollface: 
_only joking... i guess vscode is not too bad!_

2021-03-09 03:44 UTC, devkanro commented
Thanks, I will check it later.

2021-03-12 06:26 UTC, devkanro commented
@rogchap All comments have been resolved.
Please comment here if you have any other advice.

2021-03-23 03:18 UTC, rogchap approved these changes

2021-03-23 03:18 UTC, merged

2021-03-23 03:19 UTC, rogchap commented
Thanks again @devkanro and @iou90 will get this in a release soon.